
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.forensic-vfs-mount]
audit-as-crates-io = false

[[exemptions.bitflags]]
version = "2.13.1"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-run"

[[exemptions.crypto-common]]
version = "0.1.7"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-run"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.flate2]]
version = "1.1.9"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.189"
criteria = "safe-to-run"

[[exemptions.linux-raw-sys]]
version = "0.12.1"
criteria = "safe-to-run"

[[exemptions.md-5]]
version = "0.10.6"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.21.4"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.107"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.47"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "6.0.0"
criteria = "safe-to-run"

[[exemptions.rustix]]
version = "1.1.4"
criteria = "safe-to-run"

[[exemptions.sha1]]
version = "0.10.7"
criteria = "safe-to-run"

[[exemptions.simd-adler32]]
version = "0.3.10"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "3.0.3"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.19"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.19"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.20.1"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-run"
